### ISSUE TITLE
openrtm.orgの英語ページの改行を単語区切りにする

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/openrtm.org#19]
**Describe the mistakes**
openrtm.orgの英語ページで、文章の改行が単語ではなく文字数により行われているのを単語区切りに直す。

![english_page](https://user-images.githubusercontent.com/11814060/62989947-11331900-be85-11e9-9635-3f9528d4dc8c.png)

**Comment by n-ando** [comment]
もともとの設定は、Code per Node設定により、なぜか以下のように **word-break** が **break-all** (単語中などでの文字の改行に関する禁則処理を解除し、どの文字の間でも改行) に設定されていた。

- Code per Node設定: https://openrtm.org/openrtm/ja/admin/config/content/cpn

```css
/*- Global -*/
body { word-break: break-all; }
```

これを **break-word** にすることで英単語単位で開業できるが、そのままだと右端がガタガタになるので、 **text-align** に **justify** に設定することで、右端もそろったうえで英単語単位で改行
となった。

```css
/*- Global -*/
body {
    word-break: break-word;
    text-align: justify;
 }
```

![fixed_english_page](https://user-images.githubusercontent.com/11814060/62990609-8b649d00-be87-11e9-893b-5f047bf4cbb1.png)
